server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_food_db;
    username: postgres
    password: Sobirov0717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  admin:
    username: "Nurmukhammad"
    email: "snurmuhammad85@gmail.com"
    contactNumber: "944310717"
    password: "Admin.123@"

  jwt:
    secretKey: "55d2430e17864da8db7h8dbd64a63777be5c1a7f06k92197c9b8113a3b552l60"
    expireDays: 7