server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_food_db;
    username: postgres
    password: Sobirov0717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  admin:
    username: "Nurmukhammad"
    email: "snurmuhammad85@gmail.com"
    password: "Admin.123@"